let token=null,me=null;const $=s=>document.querySelector(s),today=()=>new Date().toISOString().slice(0,10);const fields=['resolved','inProgress','waiting','forward','inCall','outCall','partnerEngSupport','physicalSupport'],labels=['Resolved','In Progress','Waiting','Forward','In Call','Out Call','Partner / Eng Support','Physical Support','Ticket Work','Call Work','Support Work','Total Work'],all=[...fields,'ticketWork','callWork','supportWork','totalWork'];
async function api(p){if(!API_URL.includes('script.google.com'))throw Error('Configure API_URL in config.js');const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...p,token})}),t=await r.text();let x;try{x=JSON.parse(t)}catch(e){throw Error('Invalid backend response')}if(!x.ok)throw Error(x.message||'Request failed');return x}
function showLogin(m){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#loginMsg').textContent=m||'Only registered team accounts can access this portal.'}function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden')}
function gis(){if(!window.google?.accounts?.id){setTimeout(gis,300);return}google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:login});google.accounts.id.renderButton($('#googleBtn'),{theme:'outline',size:'large',shape:'pill',width:300})}async function login(r){try{$('#loginMsg').textContent='Signing in…';token=r.credential;const x=await api({action:'login'});me=x.user;localStorage.setItem('hs_token',token);showApp();apply();await profile();await dashboard()}catch(e){token=null;localStorage.removeItem('hs_token');showLogin(e.message)}}
function apply(){$('#userName').textContent=me.name||'User';$('#userRole').textContent=(me.role||'EMPLOYEE').replaceAll('_',' ');$('#avatar').textContent=(me.name||'U')[0].toUpperCase();if(me.role!=='EMPLOYEE')$('#adminNav').classList.remove('hidden')}
function nav(){document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden');const v=b.dataset.view;if(v==='dashboard')dashboard();if(v==='activities')activities();if(v==='monthly')monthly();if(v==='yearly')yearly();if(v==='profile')profile();if(v==='admin')admin()})}
function defaults(){$('#dashDate').value=$('#reportDate').value=$('#activityDate').value=today();const d=new Date();$('#monthInput').value=d.toISOString().slice(0,7);$('#yearInput').value=d.getFullYear();$('#reportFields').innerHTML=fields.map(k=>`<label>${labels[fields.indexOf(k)]}<input id="${k}" type="number" min="0" value="0"></label>`).join('');$('#profileFields').innerHTML=[['personalMobile','Personal Mobile'],['alternativeMobile','Alternative Mobile'],['personalEmail','Personal Email'],['bloodGroup','Blood Group'],['presentAddress','Present Address','full'],['permanentAddress','Permanent Address','full'],['emergencyName','Emergency Contact Name'],['emergencyRelation','Relationship'],['emergencyNumber','Emergency Contact Number'],['emergencyAltNumber','Alternative Emergency Number'],['emergencyAddress','Emergency Address','full'],['emergencyNotes','Emergency Notes','full']].map(x=>`<label class="${x[2]||''}">${x[1]}${x[0]==='personalEmail'?'<input id="'+x[0]+'" type="email">':'<input id="'+x[0]+'">'}</label>`).join('')}
function table(rows,id){let h='<tr>'+['Engineer',...labels].map(x=>`<th>${x}</th>`).join('')+'</tr>';rows.forEach(r=>h+='<tr>'+['engineer',...all].map(k=>`<td>${r[k]??0}</td>`).join('')+'</tr>');$(id).innerHTML=h}
async function dashboard(){try{const r=await api({action:'daily',date:$('#dashDate').value});table(r.rows||[],'#dashTable');const t={};all.forEach(k=>t[k]=(r.rows||[]).reduce((a,x)=>a+(+x[k]||0),0));$('#kpi').innerHTML=['resolved','inProgress','waiting','forward','ticketWork','totalWork'].map(k=>`<div class="kpi"><small>${labels[all.indexOf(k)]}</small><b>${t[k]||0}</b></div>`).join('');$('#dashUpdated').textContent='Updated '+new Date().toLocaleTimeString()}catch(e){$('#dashTable').innerHTML='<tr><td>'+e.message+'</td></tr>'}}
async function saveReport(){const p={action:'submit',date:$('#reportDate').value};fields.forEach(k=>p[k]=Math.max(0,+$('#'+k).value||0));try{$('#reportMsg').textContent=(await api(p)).message;dashboard()}catch(e){$('#reportMsg').textContent=e.message}}
async function activities(){try{const r=await api({action:'myActivities'});$('#activityTable').innerHTML='<tr><th>Date</th><th>Type</th><th>Reference</th><th>Status</th><th>Notes</th></tr>'+(r.rows||[]).map(x=>`<tr><td>${x.date}</td><td>${x.type}</td><td>${x.reference||''}</td><td>${x.status||''}</td><td>${x.notes||''}</td></tr>`).join('')}catch(e){$('#activityTable').innerHTML='<tr><td>'+e.message+'</td></tr>'}}
async function saveActivity(){try{const r=await api({action:'activity',type:$('#activityType').value,date:$('#activityDate').value,reference:$('#activityRef').value,status:$('#activityStatus').value,notes:$('#activityNotes').value});$('#activityMsg').textContent=r.message;$('#activityRef').value='';$('#activityNotes').value='';activities()}catch(e){$('#activityMsg').textContent=e.message}}
async function monthly(){try{const r=await api({action:'monthly',month:$('#monthInput').value});table(r.rows||[],'#monthlyTable')}catch(e){$('#monthlyTable').innerHTML='<tr><td>'+e.message+'</td></tr>'}}async function yearly(){try{const r=await api({action:'yearly',year:+$('#yearInput').value});table(r.rows||[],'#yearlyTable')}catch(e){$('#yearlyTable').innerHTML='<tr><td>'+e.message+'</td></tr>'}}
async function profile(){try{const p=(await api({action:'profile'})).profile;$('#employmentInfo').innerHTML=[['Employee ID',p.employeeId],['Name',p.name],['Department',p.department],['Designation',p.designation],['Status',p.status],['Joining Date',p.joiningDate],['Office Email',p.officeEmail]].map(x=>`<div><b>${x[0]}</b><br>${x[1]||'—'}</div>`).join('');['personalMobile','alternativeMobile','personalEmail','bloodGroup','presentAddress','permanentAddress','emergencyName','emergencyRelation','emergencyNumber','emergencyAltNumber','emergencyAddress','emergencyNotes'].forEach(k=>$('#'+k).value=p[k]||'')}catch(e){$('#profileMsg').textContent=e.message}}
async function saveProfile(){const p={action:'updateProfile'};['personalMobile','alternativeMobile','personalEmail','bloodGroup','presentAddress','permanentAddress','emergencyName','emergencyRelation','emergencyNumber','emergencyAltNumber','emergencyAddress','emergencyNotes'].forEach(k=>p[k]=$('#'+k).value.trim());try{$('#profileMsg').textContent=(await api(p)).message}catch(e){$('#profileMsg').textContent=e.message}}
async function admin(){if(me.role==='EMPLOYEE')return;try{const r=await api({action:'adminEmployees'});$('#adminContent').innerHTML='<div class="card"><div class="head"><h3>Employee Directory</h3></div><p class="muted">Admin Viewer is read-only. Salary and sensitive emergency data are never returned here.</p><div class="table-wrap"><table><tr><th>ID</th><th>Name</th><th>Office Email</th><th>Role</th><th>Status</th><th>Designation</th></tr>'+(r.rows||[]).map(x=>`<tr><td>${x.employeeId}</td><td>${x.name}</td><td>${x.officeEmail}</td><td>${x.role}</td><td>${x.status}</td><td>${x.designation||''}</td></tr>`).join('')+'</table></div></div>'}catch(e){$('#adminContent').innerHTML='<div class="card">'+e.message+'</div>'}}
function logout(){token=null;me=null;localStorage.removeItem('hs_token');try{google.accounts.id.disableAutoSelect()}catch(e){}showLogin('Signed out. Sign in again.')}
async function boot(){defaults();nav();$('#saveReport').onclick=saveReport;$('#refreshBtn').onclick=dashboard;$('#dashDate').onchange=dashboard;$('#saveActivity').onclick=saveActivity;$('#loadActivities').onclick=activities;$('#loadMonthly').onclick=monthly;$('#loadYearly').onclick=yearly;$('#saveProfile').onclick=saveProfile;$('#logoutBtn').onclick=logout;gis();const t=localStorage.getItem('hs_token');if(t){token=t;try{me=(await api({action:'login'})).user;showApp();apply();await profile();await dashboard()}catch(e){token=null;localStorage.removeItem('hs_token');showLogin('Session expired. Please sign in again.')}}}boot();setInterval(()=>{if(me&&!$('#dashboard').classList.contains('hidden'))dashboard()},AUTO_REFRESH_MS);
