const reportData = [
  {
    "sl": 1,
    "name": "Easin",
    "resolved": 3,
    "inProgress": 0,
    "waiting": 0,
    "forward": 9,
    "inCall": 0,
    "outCall": 11,
    "partnerEngSupport": 7,
    "physicalSupport": 0,
    "ticketWork": 30,
    "callWork": 57,
    "supportWork": 114,
    "totalWork": 30
  },
  {
    "sl": 2,
    "name": "Habib",
    "resolved": 41,
    "inProgress": 16,
    "waiting": 0,
    "forward": 4,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 3,
    "physicalSupport": 0,
    "ticketWork": 64,
    "callWork": 87,
    "supportWork": 158,
    "totalWork": 64
  },
  {
    "sl": 3,
    "name": "Oli",
    "resolved": 25,
    "inProgress": 27,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 1,
    "physicalSupport": 0,
    "ticketWork": 53,
    "callWork": 81,
    "supportWork": 135,
    "totalWork": 53
  },
  {
    "sl": 4,
    "name": "Ruhul",
    "resolved": 53,
    "inProgress": 13,
    "waiting": 0,
    "forward": 4,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 4,
    "physicalSupport": 0,
    "ticketWork": 74,
    "callWork": 95,
    "supportWork": 177,
    "totalWork": 74
  },
  {
    "sl": 5,
    "name": "Uzzal",
    "resolved": 32,
    "inProgress": 15,
    "waiting": 1,
    "forward": 12,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 10,
    "physicalSupport": 0,
    "ticketWork": 70,
    "callWork": 108,
    "supportWork": 201,
    "totalWork": 70
  },
  {
    "sl": 6,
    "name": "Prantha",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  },
  {
    "sl": 7,
    "name": "Marzan",
    "resolved": 47,
    "inProgress": 11,
    "waiting": 1,
    "forward": 2,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 3,
    "physicalSupport": 0,
    "ticketWork": 64,
    "callWork": 81,
    "supportWork": 151,
    "totalWork": 64
  },
  {
    "sl": 8,
    "name": "Ahasan",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  },
  {
    "sl": 9,
    "name": "Rosin",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  },
  {
    "sl": 10,
    "name": "Anjon",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  },
  {
    "sl": 11,
    "name": "Radi",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  },
  {
    "sl": 12,
    "name": "Shuvo",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  },
  {
    "sl": 13,
    "name": "Amit",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  },
  {
    "sl": 14,
    "name": "Mazhar (Intern)",
    "resolved": 0,
    "inProgress": 0,
    "waiting": 0,
    "forward": 0,
    "inCall": 0,
    "outCall": 0,
    "partnerEngSupport": 0,
    "physicalSupport": 0,
    "ticketWork": 0,
    "callWork": 0,
    "supportWork": 0,
    "totalWork": 0
  }
];
const reportTotals = {
  "resolved": 132,
  "inProgress": 39,
  "waiting": 2,
  "forward": 18,
  "inCall": 0,
  "outCall": 0,
  "partnerEngSupport": 17,
  "physicalSupport": 0,
  "ticketWork": 208,
  "callWork": 284,
  "supportWork": 529,
  "totalWork": 208
};
const reportDate = '18/09/2026';
